#Logging
logging.config: classpath:logback.xml

server:
  shutdown: graceful
  port: 9082
spring:
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  jackson-custom:
    serialization:
      local-time-format: HH:mm
      local-date-format: YYYY-MM-dd
      zoned-date-time-format: ${spring.jackson.date-format}
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_shop_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10 # Adjust as needed
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: order_pool
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
