#Logging
logging.config: classpath:logback.xml

server:
  shutdown: graceful
  port: 9083
spring:
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  jackson-custom:
    serialization:
      local-time-format: HH:mm
      local-date-format: YYYY-MM-dd
      zoned-date-time-format: ${spring.jackson.date-format}
  datasource:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      connection-test-query: SELECT 1
      # maximum number of milliseconds that a client will wait for a connection
      connection-timeout: 20000
      # minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-idle: 3
      # maximum pool size
      maximum-pool-size: 20
      # maximum idle time for connection
      idle-timeout: 10000
      # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      max-lifetime: 1000
      # default auto-commit behavior.
      auto-commit: true
      pool-name: store_pool
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/coffee_shop_store
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
      show-sql: true
      generate-ddl: true
    package-to-scan: com.dbaotrung.example.coffee.store
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
