#Logging
logging.config: classpath:logback.xml

server:
  shutdown: graceful
  port: 9082
spring:
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  main:
    allow-bean-definition-overriding: false
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
      write-date-keys-as-timestamps: true
      write-durations-as-timestamps: true
      write-enums-using-to-string: false
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  jackson-custom:
    serialization:
      local-time-format: HH:mm
      local-date-format: YYYY-MM-dd
      zoned-date-time-format: ${spring.jackson.date-format}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
